### ISSUE TITLE
Different npm install command on NPM website and git hub 

### ISSUE THREAD

**Issue by vibhorpahare** [react-native-picker/picker#168]
[https://www.npmjs.com/package/@react-native-community/picker](url)

Above given React native picker on npm website is with name @react-native-community /picker and the git hub link redirects it to this repo which is react-native-picker/picker
Is there any issue?

because I am confused about which 'npm install' command should I use, 

NPM websites say: npm i @react-native-community/picker

and this repo says: npm install @react-native-picker/picker --save

which one is correct? 

![Screenshot (20)](https://user-images.githubusercontent.com/18512213/98818733-f49fdb00-2451-11eb-8913-215751eadca7.png)

**Comment by Naturalclar** [comment]
@vibhorpahare sorry for the confusion. Please use `@react-native-picker/picker` instead of `@react-native-community/picker` for the latest version.

We are slowly migrating modules out of `@react-native-community` namespace. For details, please see this issue comment https://github.com/react-native-community/discussions-and-proposals/issues/176#issuecomment-693569246

I'll ask for there to be a deprecation notice on the npm page.
